POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "KYRIE IRVING FAN",
    "author": "LBJ",
    "url": "miami.com",
    "likes": 6666,
    "userId": "607461fee511b670a1530fc5"
}
