POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "JIMMY's BLOG",
    "author": "Jimmy",
    "url": "jimmy.com",
    "likes": 100000,
    "userId": "60740557e0752c615f83a427"
}
